import type { PaperEntry } from "./types";

const allPapers: PaperEntry[] = [
  // ====== Std 12 Question Banks (Official SCERT) ======
  {
    id: "qb12-physics-2023",
    standard: 12,
    subjectId: "physics",
    year: 2023,
    title: "Physics Question Bank 2023 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Physics. Chapter-wise MCQs, short answer, and long answer questions covering all 16 chapters.",
    url: "/papers/Std12_Physics_QuestionBank_2023.pdf",
    local: true,
  },
  {
    id: "qb12-chemistry-2023",
    standard: 12,
    subjectId: "chemistry",
    year: 2023,
    title: "Chemistry Question Bank 2023 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Chemistry. Chapter-wise questions with answers covering all 16 chapters.",
    url: "/papers/Std12_Chemistry_QuestionBank_2023.pdf",
    local: true,
  },
  {
    id: "qb12-biology-2023",
    standard: 12,
    subjectId: "biology",
    year: 2023,
    title: "Biology Question Bank 2023 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Biology. Chapter-wise MCQs, short answer, and long answer questions covering all 15 chapters.",
    url: "/papers/Std12_Biology_QuestionBank_2023.pdf",
    local: true,
  },
  {
    id: "qb12-maths-2023",
    standard: 12,
    subjectId: "maths",
    year: 2023,
    title: "Maths & Statistics Question Bank 2023 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Mathematics & Statistics. Chapter-wise questions for Part I and Part II.",
    url: "/papers/Std12_Maths_QuestionBank_2023.pdf",
    local: true,
  },
  {
    id: "qb12-physics-2024",
    standard: 12,
    subjectId: "physics",
    year: 2024,
    title: "Physics Question Bank 2024 (SCERT - Supplementary)",
    type: "question-bank",
    description: "Comprehensive support learning material for Physics. Designed for students appearing for supplementary exams with chapter-wise questions.",
    url: "/papers/Std12_Physics_QuestionBank_2024.pdf",
    local: true,
  },
  {
    id: "qb12-chemistry-2024",
    standard: 12,
    subjectId: "chemistry",
    year: 2024,
    title: "Chemistry Question Bank 2024 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Chemistry 2024. 500+ questions with detailed distribution across all chapters.",
    url: "/papers/Std12_Chemistry_QuestionBank_2024.pdf",
    local: true,
  },
  {
    id: "qb12-biology-2024",
    standard: 12,
    subjectId: "biology",
    year: 2024,
    title: "Biology Question Bank 2024 (SCERT - Supplementary)",
    type: "question-bank",
    description: "Comprehensive support learning material for Biology. Chapter-wise questions with model question paper for supplementary exam preparation.",
    url: "/papers/Std12_Biology_QuestionBank_2024.pdf",
    local: true,
  },
  {
    id: "qb12-physics-2022",
    standard: 12,
    subjectId: "physics",
    year: 2022,
    title: "Physics Question Bank 2022 (SCERT)",
    type: "question-bank",
    description: "Official SCERT Maharashtra question bank for Std 12 Physics 2022. Contains MCQ, VSA, SA and LA questions chapter-wise.",
    url: "/papers/Std12_Physics_QuestionBank_2022.pdf",
    local: true,
  },

  // ====== Std 12 Board Exam PYQs (External Links) ======
  {
    id: "pyq12-physics-2024",
    standard: 12,
    subjectId: "physics",
    year: 2024,
    month: "Feb",
    title: "Physics Board Exam 2024",
    type: "board-exam",
    description: "Maharashtra HSC Physics board exam question paper - February/March 2024 (70 marks, 3 hours).",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-class-physics-12th-standard-board-exam-2023-2024-official_20075",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-chemistry-2024",
    standard: 12,
    subjectId: "chemistry",
    year: 2024,
    month: "Feb",
    title: "Chemistry Board Exam 2024",
    type: "board-exam",
    description: "Maharashtra HSC Chemistry board exam question paper - February/March 2024 (70 marks, 3 hours).",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-chemistry-12th-standard-board-exam-2023-2024-official_20077",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-maths-2024",
    standard: 12,
    subjectId: "maths",
    year: 2024,
    month: "Feb",
    title: "Maths & Statistics Board Exam 2024",
    type: "board-exam",
    description: "Maharashtra HSC Mathematics & Statistics board exam question paper - February/March 2024 (80 marks, 3 hours).",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-mathematics-statistics-arts-science-12th-standard-board-exam-2023-2024-official_20078",
    local: false,
    marks: 80,
    duration: "3 hours",
  },
  {
    id: "pyq12-biology-2024",
    standard: 12,
    subjectId: "biology",
    year: 2024,
    month: "Feb",
    title: "Biology Board Exam 2024",
    type: "board-exam",
    description: "Maharashtra HSC Biology board exam question paper - February/March 2024 (70 marks, 3 hours).",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-biology-12th-standard-board-exam-2023-2024-official_20079",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-physics-2023",
    standard: 12,
    subjectId: "physics",
    year: 2023,
    month: "Feb",
    title: "Physics Board Exam 2023",
    type: "board-exam",
    description: "Maharashtra HSC Physics board exam question paper - February/March 2023.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-physics-12th-standard-board-exam-2022-2023-official_20076",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-chemistry-2023",
    standard: 12,
    subjectId: "chemistry",
    year: 2023,
    month: "Feb",
    title: "Chemistry Board Exam 2023",
    type: "board-exam",
    description: "Maharashtra HSC Chemistry board exam question paper - February/March 2023.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-chemistry-12th-standard-board-exam-2022-2023-official_20109",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-maths-2023",
    standard: 12,
    subjectId: "maths",
    year: 2023,
    month: "Feb",
    title: "Maths & Statistics Board Exam 2023",
    type: "board-exam",
    description: "Maharashtra HSC Mathematics & Statistics board exam question paper - February/March 2023.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-mathematics-statistics-arts-science-12th-standard-board-exam-2022-2023-official_20111",
    local: false,
    marks: 80,
    duration: "3 hours",
  },
  {
    id: "pyq12-biology-2023",
    standard: 12,
    subjectId: "biology",
    year: 2023,
    month: "Feb",
    title: "Biology Board Exam 2023",
    type: "board-exam",
    description: "Maharashtra HSC Biology board exam question paper - February/March 2023.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-biology-12th-standard-board-exam-2022-2023-official_20110",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-physics-2022",
    standard: 12,
    subjectId: "physics",
    year: 2022,
    month: "Feb",
    title: "Physics Board Exam 2022",
    type: "board-exam",
    description: "Maharashtra HSC Physics board exam question paper - February/March 2022.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-physics-12th-standard-board-exam-2021-2022-official_20106",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-chemistry-2022",
    standard: 12,
    subjectId: "chemistry",
    year: 2022,
    month: "Feb",
    title: "Chemistry Board Exam 2022",
    type: "board-exam",
    description: "Maharashtra HSC Chemistry board exam question paper - February/March 2022.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-chemistry-12th-standard-board-exam-2021-2022-official_20108",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-maths-2022",
    standard: 12,
    subjectId: "maths",
    year: 2022,
    month: "Feb",
    title: "Maths & Statistics Board Exam 2022",
    type: "board-exam",
    description: "Maharashtra HSC Mathematics & Statistics board exam question paper - February/March 2022.",
    url: "https://collegedunia.com/exams/msbshse/question-paper-2022",
    local: false,
    marks: 80,
    duration: "3 hours",
  },
  {
    id: "pyq12-biology-2022",
    standard: 12,
    subjectId: "biology",
    year: 2022,
    month: "Feb",
    title: "Biology Board Exam 2022",
    type: "board-exam",
    description: "Maharashtra HSC Biology board exam question paper - February/March 2022.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-biology-12th-standard-board-exam-2021-2022-official_20107",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-physics-2020",
    standard: 12,
    subjectId: "physics",
    year: 2020,
    month: "Feb",
    title: "Physics Board Exam 2020",
    type: "board-exam",
    description: "Maharashtra HSC Physics board exam question paper - February/March 2020.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-physics-12th-standard-board-exam-2019-2020-official_20104",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-chemistry-2020",
    standard: 12,
    subjectId: "chemistry",
    year: 2020,
    month: "Feb",
    title: "Chemistry Board Exam 2020",
    type: "board-exam",
    description: "Maharashtra HSC Chemistry board exam question paper - February/March 2020.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-chemistry-12th-standard-board-exam-2019-2020-official_20102",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "pyq12-maths-2020",
    standard: 12,
    subjectId: "maths",
    year: 2020,
    month: "Feb",
    title: "Maths & Statistics Board Exam 2020",
    type: "board-exam",
    description: "Maharashtra HSC Mathematics & Statistics board exam question paper - February/March 2020.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-mathematics-statistics-12th-standard-board-exam-2019-2020-official_20100",
    local: false,
    marks: 80,
    duration: "3 hours",
  },
  {
    id: "pyq12-biology-2020",
    standard: 12,
    subjectId: "biology",
    year: 2020,
    month: "Feb",
    title: "Biology Board Exam 2020",
    type: "board-exam",
    description: "Maharashtra HSC Biology board exam question paper - February/March 2020.",
    url: "https://www.shaalaa.com/question-paper-solution/maharashtra-board-hsc-biology-12th-standard-board-exam-2019-2020-official_20103",
    local: false,
    marks: 70,
    duration: "3 hours",
  },

  // ====== Std 12 Sample Papers ======
  {
    id: "sp12-physics-2025",
    standard: 12,
    subjectId: "physics",
    year: 2025,
    title: "Physics Sample Paper 2025",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Physics sample question paper based on latest exam pattern.",
    url: "https://www.jagranjosh.com/articles/maharashtra-board-hsc-subject-wise-sample-papers-pdf-download-1800006494-1",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-chemistry-2025",
    standard: 12,
    subjectId: "chemistry",
    year: 2025,
    title: "Chemistry Sample Paper 2025",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Chemistry sample question paper with marking scheme.",
    url: "https://www.collegedekho.com/maharashtra-hsc-chemistry-sample-paper-brd",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-biology-2025",
    standard: 12,
    subjectId: "biology",
    year: 2025,
    title: "Biology Sample Paper 2025",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Biology sample question paper with 30 questions across 4 sections.",
    url: "https://www.collegedekho.com/maharashtra-hsc-biology-sample-paper-brd",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-maths-2025",
    standard: 12,
    subjectId: "maths",
    year: 2025,
    title: "Maths & Statistics Sample Paper 2025",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Mathematics & Statistics sample question paper.",
    url: "https://www.jagranjosh.com/articles/maharashtra-board-hsc-subject-wise-sample-papers-pdf-download-1800006494-1",
    local: false,
    marks: 80,
    duration: "3 hours",
  },
  {
    id: "sp12-physics-2024",
    standard: 12,
    subjectId: "physics",
    year: 2024,
    title: "Physics Sample Paper 2024",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Physics sample paper 2024 with solutions.",
    url: "https://www.getmyuni.com/boards/maharashtra-hsc-sample-papers",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-chemistry-2024",
    standard: 12,
    subjectId: "chemistry",
    year: 2024,
    title: "Chemistry Sample Paper 2024",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Chemistry sample paper 2024 with solutions.",
    url: "https://www.getmyuni.com/boards/maharashtra-hsc-sample-papers",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-biology-2024",
    standard: 12,
    subjectId: "biology",
    year: 2024,
    title: "Biology Sample Paper 2024",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Biology sample paper 2024 with solutions.",
    url: "https://www.getmyuni.com/boards/maharashtra-hsc-sample-papers",
    local: false,
    marks: 70,
    duration: "3 hours",
  },
  {
    id: "sp12-maths-2024",
    standard: 12,
    subjectId: "maths",
    year: 2024,
    title: "Maths & Statistics Sample Paper 2024",
    type: "sample-paper",
    description: "MSBSHSE Class 12 Mathematics & Statistics sample paper 2024.",
    url: "https://www.getmyuni.com/boards/maharashtra-hsc-sample-papers",
    local: false,
    marks: 80,
    duration: "3 hours",
  },

  // ====== Std 11 Question Banks (External Links) ======
  {
    id: "qb11-physics-2023",
    standard: 11,
    subjectId: "physics",
    year: 2023,
    title: "Physics Question Bank 2023",
    type: "question-bank",
    description: "SCERT Maharashtra Std 11 Physics question bank with chapter-wise questions.",
    url: "https://www.shaalaa.com/search-question-bank-solutions/maharashtra-board-11th-standard-hsc-science-general_156?subjects=physics_7792",
    local: false,
  },
  {
    id: "qb11-chemistry-2023",
    standard: 11,
    subjectId: "chemistry",
    year: 2023,
    title: "Chemistry Question Bank 2023",
    type: "question-bank",
    description: "SCERT Maharashtra Std 11 Chemistry question bank with chapter-wise questions.",
    url: "https://www.shaalaa.com/search-question-bank-solutions/maharashtra-board-11th-standard-hsc-science-general_156?subjects=chemistry_7793",
    local: false,
  },
  {
    id: "qb11-biology-2023",
    standard: 11,
    subjectId: "biology",
    year: 2023,
    title: "Biology Question Bank 2023",
    type: "question-bank",
    description: "SCERT Maharashtra Std 11 Biology question bank with chapter-wise questions.",
    url: "https://www.shaalaa.com/search-question-bank-solutions/maharashtra-board-11th-standard-hsc-science-general_156?subjects=biology_7794",
    local: false,
  },
  {
    id: "qb11-maths-2023",
    standard: 11,
    subjectId: "maths",
    year: 2023,
    title: "Maths Question Bank 2023",
    type: "question-bank",
    description: "SCERT Maharashtra Std 11 Mathematics question bank with chapter-wise questions.",
    url: "https://www.shaalaa.com/search-question-bank-solutions/maharashtra-board-11th-standard-hsc-science-general_156?subjects=mathematics_7795",
    local: false,
  },
];

export function getPapers(
  standard?: number,
  subjectId?: string,
  type?: string,
  year?: number
): PaperEntry[] {
  let filtered = allPapers;
  if (standard) filtered = filtered.filter((p) => p.standard === standard);
  if (subjectId) filtered = filtered.filter((p) => p.subjectId === subjectId);
  if (type) filtered = filtered.filter((p) => p.type === type);
  if (year) filtered = filtered.filter((p) => p.year === year);
  return filtered.sort((a, b) => b.year - a.year || a.standard - b.standard);
}

export function getPaperTypes(): string[] {
  return [...new Set(allPapers.map((p) => p.type))];
}

export function getStandards(): number[] {
  return [...new Set(allPapers.map((p) => p.standard))].sort();
}

export function getPaperYears(): number[] {
  return [...new Set(allPapers.map((p) => p.year))].sort((a, b) => b - a);
}

export type { PaperEntry };
